#!/usr/bin/env bash
#install nginx

sudo apt  install  -y nginx
sudo apt -y update
sudo apt upgrade
echo "Hello World!" |sudo tee /var/www/html/index.html
line = 'server '
sudo systemctl start nginx
sudo systemctl enable nginx
