#!/usr/bin/env bash
#redirection

sudo echo "events {

 }

   http {
     server {
	    listen 80;
            server_name enee.tech;
 
            root /var/www/html/;

            location /redirect_me {
	    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
            }
       }
}" > /etc/nginx/nginx.conf
sudo nginx -t
sudo nginx -s reload
