#!/usr/bin/env bash
#install haproxy

sudo apt install haproxy -y

new_string = "frontend http\n\tbind *:80\n\tdefault_backend my_backend\nbackend\n\tbalance roundrobin\n\tserver 310587-web-01 3.80.18.107\n\tserver 310587-web-02 100.25.132.152"

echo -e "$new_string" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo systemctl enable haproxy
sudo sysemctl start haproxy
sudo systemctl restart haproxy
