#!/usr/bin/env bash
#install haproxy

sudo apt-get -y update
sudo apt install haproxy -y

new_string=\
"
frontend http
	bind *:80
	default_backend my_backend
backend
	balance roundrobin
	server 310587-web-01 3.80.18.107 check
	server 310587-web-02 100.25.132.152 check
"

echo  "$new_string" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo systemctl enable haproxy
sudo sysemctl start haproxy
sudo systemctl restart haproxy
